name: Android CI

on:
  push:
    branches: master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Check gradle version
      run: gradle --version

    - name: Init gradle wrapper
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
