name: Android CI

on:
  push:
    branches: 
    - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
        # with:
        #     sparse-checkout: 'android'
        #     sparse-checkout-cone-mode: false
      
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Run Yarn Install
        run: | 
              npm install -g yarn
              yarn install

      - name: Build App
        run: |
              cd ./android
              ./gradlew assembleRelease

      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v4
        
      # - name: Build with Gradle
      #   run: ./gradlew build

      # - name: Check gradle version
      #   run: gradle --version

      # - name: Init gradle wrapper
      #   run: gradle wrapper
        
      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
        
      # - name: Build with Gradle
      #   run: ./gradlew build
